(inner_quote)      @constant.character.escape
(character_vector) @string
(number)           @constant.numeric
(zilde)            @constant.builtin
(comment)          @comment.line
(system)           @variable.builtin
(parameter)        @variable.parameter
(identifier)       @variable
(end_stmt)         @punctuation.delimiter
(colon)            @punctuation.delimiter
(semicolon)        @punctuation.delimiter
(lparen)           @punctuation.bracket
(rparen)           @punctuation.bracket
(lbrace)           @punctuation.bracket
(rbrace)           @punctuation.bracket
(lsquare)          @punctuation.bracket
(rsquare)          @punctuation.bracket
(primitive)        @function

